repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: ["--line-length=125"]
        types: [file, python]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--line-length=125", "--profile=black"]
        types: [file, python]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--ignore=E203,W503,W605", "--max-line-length=125"]
        types: [file, python]

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
      - id: autopep8
        args:
          [
            '--ignore=["E203","W503","W605"]',
            "--max-line-length=125",
            "--in-place"
          ]
        types: [file, python]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [ file ]
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [ file ]

  - repo: https://github.com/sbrunner/pre-commit-copyright
    rev: 0.7.0
    hooks:
      - id: copyright
        name: update copyright
        exclude: |
          (?x)^(
            ^\..+|
            .+\.md|
            documentation/.*|
            lib/accounts/.*|
            cdk.json|
            jest.config.ts|
            LICENSE|
            package.json|
            package-lock.json|
            tsconfig.json|
          )$
      - id: copyright-required
        name: require copyright
        exclude: |
          (?x)^(
            ^\..+|
            .+\.md|
            documentation/.*|
            lib/accounts/.*|
            cdk.json|
            jest.config.ts|
            LICENSE|
            package.json|
            package-lock.json|
            tsconfig.json|
          )$
