name: ❓ Question
description: General question for OSML
labels: "question"
projects: "aws-solutions-library-samples/5"

body:
  - type: textarea
    id: description
    attributes:
      label: Question / Clarification
      description: Please post your question(s) here
    validations:
      required: true
