version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - sed -i "s/git@github.com:/https:\/\/github.com\//" .gitmodules
      - if [[ "${BASE_REF}" -eq "dev" ]]; then jq '(.buildModelContainer, .buildAppContainer) = true' lib/accounts/target_account_template.json > lib/accounts/target_account.json; fi
      - sed -i "s/1234567890123/$AWS_ACCOUNT/" lib/accounts/target_account.json
      - sed -i "s/fake-alias/$NAME/" lib/accounts/target_account.json
      - sed -i "s/us-west-1/$AWS_DEFAULT_REGION/" lib/accounts/target_account.json
      - cat lib/accounts/target_account.json
      - yum install -y git-lfs
      - git-lfs pull
      - git submodule update --init --recursive
      - npm i
      - npm install -g aws-cdk
  build:
    commands:
      - cdk bootstrap --force
      - npm run deploy
  post_build:
    commands:
      - echo Build completed on `date`
