version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - sed -i "s/git@github.com:/https:\/\/github.com\//" .gitmodules
      - git submodule update --init --recursive
      - |
        if [[ "$BASE_REF" == "dev" ]]; then
          echo "Building from source"
          export BUILD_FROM_SOURCE=true
        else
          echo "Not building from source"
        fi
      - cp lib/accounts/target_account_template.json lib/accounts/target_account.json
      - cp lib/accounts/target_auth_template.json lib/accounts/target_auth.json
      - sed -i "s/1234567890123/$AWS_ACCOUNT/" lib/accounts/target_account.json
      - sed -i "s/fake-alias/$NAME/" lib/accounts/target_account.json
      - sed -i "s/us-west-1/$AWS_DEFAULT_REGION/" lib/accounts/target_account.json
      - cat lib/accounts/target_account.json
      - yum install -y git-lfs
      - git lfs pull
      - git submodule foreach git lfs pull
      - npm i
      - npm install -g aws-cdk
  build:
    commands:
      - cdk bootstrap --force
      - npm run deploy
  post_build:
    commands:
      - echo Build completed on `date`
