version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - sed -i "s/git@github.com:/https:\/\/github.com\//" .gitmodules
      - git submodule update --init --recursive
      - |
        if [[ "${BASE_REF}" -eq "dev" ]]; then
          export BUILD_FROM_SOURCE=true
          cp package.json package_tmp.json;
          jq '(.devDependencies."osml-cdk-constructs") = "file:lib/osml-cdk-constructs"' package_tmp.json > package.json;
          cat package.json;
          cd lib/osml-cdk-constructs;
          npm i;
          npm i --save-dev @types/jest;
          npm run build;
          cd ../../;
          rm package_tmp.json;
        fi
      - cp lib/accounts/target_account_template.json lib/accounts/target_account.json
      - sed -i "s/1234567890123/$AWS_ACCOUNT/" lib/accounts/target_account.json
      - sed -i "s/fake-alias/$NAME/" lib/accounts/target_account.json
      - sed -i "s/us-west-1/$AWS_DEFAULT_REGION/" lib/accounts/target_account.json
      - sed -i "s/false/true/" lib/accounts/target_account.json
      - cat lib/accounts/target_account.json
      - yum install -y git-lfs
      - git-lfs pull
      - npm i
      - npm install -g aws-cdk
  build:
    commands:
      - export RUN_CDK_NAG=true
      - echo ${UNIQUE_FILE_ID}
      - npm i
      - cdk synth; EXITCODE=$?
      - mkdir cdk_nag_report
      - cp -r cdk.out/*-NagReport.csv cdk_nag_report/
      - cd cdk_nag_report
      - pip install csvkit
      - csvstack NIST.800.53.R5-*.csv > NIST.800.53.R5-cdk-nag.csv
      - csvstack AwsSolutions-*.csv > AwsSolutions-cdk-nag.csv
      - csvcut -c "Rule ID","Resource ID","Compliance","Exception Reason","Rule Level","Rule Info" NIST.800.53.R5-cdk-nag.csv | csvgrep -c Compliance -m Non-Compliant > NIST.800.53.R5-violations.csv
      - csvcut -c "Rule ID","Resource ID","Compliance","Exception Reason","Rule Level","Rule Info" AwsSolutions-cdk-nag.csv | csvgrep -c Compliance -m Non-Compliant > AwsSolutions-violations.csv
      - pip install csv2md
      - csv2md NIST.800.53.R5-violations.csv > NIST.800.53.R5-violations-${UNIQUE_FILE_ID}.md
      - csv2md AwsSolutions-violations.csv > AwsSolutions-violations-${UNIQUE_FILE_ID}.md
      - cat NIST.800.53.R5-violations-${UNIQUE_FILE_ID}.md
      - cat AwsSolutions-violations-${UNIQUE_FILE_ID}.md
      - aws s3 cp NIST.800.53.R5-violations-${UNIQUE_FILE_ID}.md s3://osml-cdk-nag-reports-github/
      - aws s3 cp AwsSolutions-violations-${UNIQUE_FILE_ID}.md s3://osml-cdk-nag-reports-github/
  post_build:
    commands:
      - echo Build completed on `date`
