version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g aws-cdk

  pre_build:
    commands:
      - yum install -y git-lfs
      - cp .github/cdk.context.github.json cdk.context.json
      - git submodule update --init --recursive
      - |
        if [[ "$BASE_REF" == "dev" ]]; then
          echo "Building from source"
          sed -i 's/"BUILD_FROM_SOURCE": false,/"BUILD_FROM_SOURCE": true,/' cdk.context.json
        else
          echo "Not building from source"
        fi
      - sed -i "s/1234567890123/$AWS_ACCOUNT/" cdk.context.json
      - cat cdk.context.json
      - git lfs pull
      - git submodule foreach git lfs pull
      - npm install

  build:
    commands:
      - |
        if [[ "$BASE_REF" == "dev" ]]; then
          npm run destroy:minimal
        else
          npm run destroy
        fi

  post_build:
    commands:
      - echo "Destroy completed on $(date)"
