version: 0.2
phases:
  pre_build:
    commands:
      - sed -i "s/git@github.com:/https:\/\/github.com\//" .gitmodules
      - git submodule update --init --recursive
      - |
        if [[ "$BASE_REF" == "dev" ]]; then
          export BUILD_FROM_SOURCE=true
        else
          echo "Not building from source"
        fi
      - cp lib/accounts/target_account_template.json lib/accounts/target_account.json
      - sed -i "s/1234567890123/$AWS_ACCOUNT/" lib/accounts/target_account.json
      - sed -i "s/fake-alias/$NAME/" lib/accounts/target_account.json
      - sed -i "s/us-west-1/$AWS_DEFAULT_REGION/" lib/accounts/target_account.json
      - cat lib/accounts/target_account.json
      - npm i
      - npm install -g aws-cdk
  build:
    commands:
      - |
        if [[ "$BASE_REF" == "dev" ]]; then
          npm run destroy:minimal
        else
          npm run destroy
        fi
  post_build:
    commands:
      - echo Destroy completed on `date`
