version: 0.2
phases:
  pre_build:
    commands:
      - git submodule update --init --recursive
      - python3 -m pip install lib/osml-model-runner-test/
  build:
    commands:
      - bash scripts/model_runner_integ.sh
