version: 0.2
phases:
  pre_build:
    commands:
      - git submodule update --init --recursive
      - python3 -m pip install lib/osml-model-runner-test/
  build:
    commands:
      - python3 ./lib/osml-model-runner-test/bin/process_image.py --image ${TEST_IMAGE} --model ${TEST_MODEL}
