name: Run CDK-Nag

on:
  pull_request:
    branches:
      - dev
      - main

env:
  AWS_REGION: "us-west-2"
  AWS_PAGER: ""
  UNIQUE_FILE_ID: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}

jobs:
  run-cdk-nag:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::${{ secrets[format('OSML_{0}', github.base_ref)] }}:role/GithubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          role-duration-seconds: 7200
      - name: Run CDK Nag
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: CodeBuild-CDKNagOSML
          buildspec-override: .github/codebuild/cdk-nag.yml
          env-vars-for-codebuild: |
            BASE_REF,
            UNIQUE_FILE_ID
        env:
          BASE_REF: ${{ github.base_ref }}
          UNIQUE_FILE_ID: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
      - name: Download S3 Files
        run: |
          aws s3 cp s3://osml-cdk-nag-reports-github/NIST.800.53.R5-violations-${{ env.UNIQUE_FILE_ID }}.md NIST.800.53.R5-violations.md
          aws s3 cp s3://osml-cdk-nag-reports-github/AwsSolutions-violations-${{ env.UNIQUE_FILE_ID }}.md AwsSolutions-violations.md
      - name: Comment to the PR with violation(s)
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const nistFile = fs.readFileSync("NIST.800.53.R5-violations.md", "utf8");
            const awsFile = fs.readFileSync("AwsSolutions-violations.md", "utf8");
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Please review the existing CDK-Nag Violations!
            <details close>

            <summary>AwsSolutions Violation(s)</summary>
            ${awsFile}
            </details>

            <details close>

            <summary>NIST.800.53.R5 Violation(s)</summary>
            ${nistFile}
            </details>
              `
            })
