name: Update Submodules

on:
  pull_request:
    branches: ["dev"]

jobs:
  update_submodules:
    name: Update Submodules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true
          fetch-depth: 0
      - name: Checkout ${{ github.ref_name }} branch for each of the submodules
        run: |
          git submodule update --init --recursive --remote lib/osml-model-runner
          git submodule set-branch --branch ${{ github.ref_name }} lib/osml-model-runner
          cd lib/osml-model-runner
          git checkout ${{ github.ref_name }}
          cd ../../
          git checkout .gitmodules
      - name: Run Git Status
        run: git status
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: ${{ github.ref_name }}
          branch: Updates/submodule-${{ inputs.DISPATCH_REPO_NAME }}-updates
          title: "release: osml-model-runner@${{ github.ref_name }} - commit_Id"
          commit-message: "release: osml-model-runner@${{ github.ref_name }} - commit_Id"
          labels: automated-bot
